# Generated by Django 5.2.3 on 2025-07-01 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_clinica_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MascotaAdopcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("edad", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="mascotas/"),
                ),
                ("publicado", models.BooleanField(default=False)),
                (
                    "publicado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
