# Generated by Django 5.2.3 on 2025-07-10 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_mascotaadopcion_delete_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clinica",
            name="email_contacto",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mascotaadopcion",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Perro"), ("gato", "Gato"), ("otro", "Otro")],
                default="otro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mascotaadopcion",
            name="raza",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="mascotaadopcion",
            name="sexo",
            field=models.CharField(
                choices=[("macho", "Macho"), ("hembra", "Hembra")],
                default="macho",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mascotaadopcion",
            name="imagen",
            field=models.ImageField(
                blank=True, null=True, upload_to="mascotas_adopcion/"
            ),
        ),
        migrations.AlterField(
            model_name="mascotaadopcion",
            name="publicado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mascotas_publicadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClinicaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_with_profile",
                        to="core.clinica",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinica_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolicitudAdopcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=200)),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=255)),
                (
                    "tipo_vivienda",
                    models.CharField(
                        choices=[
                            ("casa_patio", "Casa con Patio"),
                            ("casa_sin_patio", "Casa sin Patio"),
                            ("departamento", "Departamento"),
                            ("otros", "Otros"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "situacion_vivienda",
                    models.CharField(
                        choices=[
                            ("propietario", "Soy Propietario(a)"),
                            ("arrendatario", "Soy Arrendatario(a)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "permiso_arrendador",
                    models.CharField(
                        blank=True,
                        choices=[("si", "Sí"), ("no", "No")],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("num_adultos", models.IntegerField()),
                ("num_ninos", models.IntegerField(default=0)),
                ("edades_ninos", models.TextField(blank=True, null=True)),
                ("otras_mascotas", models.TextField(blank=True, null=True)),
                (
                    "tiempo_solo",
                    models.CharField(
                        choices=[
                            ("0-2", "0-2 horas"),
                            ("2-4", "2-4 horas"),
                            ("4-6", "4-6 horas"),
                            ("6+", "Más de 6 horas"),
                        ],
                        max_length=10,
                    ),
                ),
                ("experiencia_previa", models.TextField()),
                (
                    "gastos_compromiso",
                    models.CharField(
                        choices=[
                            ("si", "Sí, completamente"),
                            ("limitado", "Sí, con algunas limitaciones"),
                            ("no_seguro", "No estoy seguro(a)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "esterilizacion_compromiso",
                    models.CharField(
                        choices=[
                            ("si", "Sí, lo comprendo y estoy dispuesto(a)"),
                            ("no", "No"),
                        ],
                        max_length=5,
                    ),
                ),
                ("planes_futuro", models.TextField()),
                ("declaracion_verdadera", models.BooleanField()),
                ("acepto_terminos", models.BooleanField()),
                (
                    "fecha_solicitud",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("revisada", "Revisada"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("contactado", "Contactado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes_recibidas",
                        to="core.clinica",
                    ),
                ),
                (
                    "mascota_adopcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="core.mascotaadopcion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solicitud de Adopción",
                "verbose_name_plural": "Solicitudes de Adopción",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
