# Generated by Django 5.2.3 on 2025-07-12 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_clinica_email_contacto_mascotaadopcion_especie_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solicitudadopcion",
            name="clinica",
        ),
        migrations.RemoveField(
            model_name="solicitudadopcion",
            name="mascota_adopcion",
        ),
        migrations.RemoveField(
            model_name="clinica",
            name="email_contacto",
        ),
        migrations.RemoveField(
            model_name="mascotaadopcion",
            name="especie",
        ),
        migrations.RemoveField(
            model_name="mascotaadopcion",
            name="raza",
        ),
        migrations.RemoveField(
            model_name="mascotaadopcion",
            name="sexo",
        ),
        migrations.AddField(
            model_name="mascota",
            name="clinica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mascotas_publicadas",
                to="core.clinica",
            ),
        ),
        migrations.AddField(
            model_name="mascota",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Perro"), ("gato", "Gato"), ("otro", "Otro")],
                default="perro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mascota",
            name="raza",
            field=models.CharField(
                blank=True,
                choices=[
                    ("labrador", "Labrador"),
                    ("pastor_aleman", "Pastor Alemán"),
                    ("mestizo", "Mestizo"),
                ],
                default="mestizo",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mascota",
            name="sexo",
            field=models.CharField(
                choices=[("macho", "Macho"), ("hembra", "Hembra")],
                default="macho",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="mascota",
            name="unidad_edad",
            field=models.CharField(
                choices=[("meses", "Meses"), ("años", "Años")],
                default="años",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="mascota",
            name="edad",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="mascotaadopcion",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="mascotas/"),
        ),
        migrations.AlterField(
            model_name="mascotaadopcion",
            name="publicado_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="ClinicaProfile",
        ),
        migrations.DeleteModel(
            name="SolicitudAdopcion",
        ),
    ]
