# Generated by Django 5.2.3 on 2025-07-05 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="estado",
            field=models.CharField(default="pendiente", max_length=20),
        ),
        migrations.AddField(
            model_name="pedido",
            name="farmacia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos_farmacia",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
