# Generated by Django 5.2.3 on 2025-07-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="perfiles/default.png",
                null=True,
                upload_to="perfiles/",
            ),
        ),
    ]
