# Generated by Django 5.2.3 on 2025-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="perfil_publicado",
            field=models.BooleanField(default=False),
        ),
    ]
