# Generated by Django 5.2.3 on 2025-07-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile_perfil_publicado"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="direccion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="nombre_clinica",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="telefono",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
