# Generated by Django 5.2.3 on 2025-07-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_direccion_profile_nombre_clinica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
