# Generated by Django 5.2.3 on 2025-07-14 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_ciudad_profile_region"),
        ("ubicacion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ciudad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ubicacion.ciudad",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ubicacion.region",
            ),
        ),
    ]
