# Generated by Django 5.2.3 on 2025-07-01 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0002_alter_mascotaenadopcion_estado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Perro"), ("gato", "Gato"), ("otro", "Otro")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("publicada", "Publicada"),
                    ("revisada", "Revisada"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="mascotas/"),
        ),
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="publicada_por",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
