# Generated by Django 5.2.3 on 2025-07-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0003_alter_mascotaenadopcion_especie_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Canino"), ("gato", "Felino"), ("otro", "Otro")],
                max_length=20,
            ),
        ),
    ]
