# Generated by Django 5.2.3 on 2025-07-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0004_alter_mascotaenadopcion_especie"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascotaenadopcion",
            name="raza",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
