# Generated by Django 5.2.3 on 2025-07-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0005_mascotaenadopcion_raza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Canino"), ("gato", "Felino")], max_length=20
            ),
        ),
    ]
