# Generated by Django 5.2.3 on 2025-07-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0006_alter_mascotaenadopcion_especie"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascotaenadopcion",
            name="sexo",
            field=models.CharField(
                choices=[
                    ("macho", "Macho"),
                    ("hembra", "Hembra"),
                    ("desconocido", "Desconocido"),
                ],
                default="desconocido",
                max_length=15,
                verbose_name="Sexo",
            ),
        ),
    ]
