# Generated by Django 5.2.3 on 2025-07-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0007_mascotaenadopcion_sexo"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascotaenadopcion",
            name="unidad_edad",
            field=models.CharField(
                choices=[("años", "Años"), ("meses", "Meses")],
                default="años",
                max_length=10,
                verbose_name="Unidad de Edad",
            ),
        ),
        migrations.AlterField(
            model_name="mascotaenadopcion",
            name="edad",
            field=models.PositiveIntegerField(
                help_text="Número de años o meses", verbose_name="Edad"
            ),
        ),
    ]
