# Generated by Django 5.2.3 on 2025-07-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0009_alter_mascotaenadopcion_especie"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudAdopcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=100)),
                ("dni", models.CharField(blank=True, max_length=20, null=True)),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.TextField()),
                ("tipo_vivienda", models.CharField(max_length=50)),
                ("situacion_vivienda", models.CharField(max_length=20)),
                (
                    "permiso_arrendador",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("num_adultos", models.IntegerField()),
                ("num_ninos", models.IntegerField()),
                ("edades_ninos", models.TextField(blank=True, null=True)),
                (
                    "otras_mascotas",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tiempo_solo", models.CharField(max_length=20)),
                ("experiencia_previa", models.TextField()),
                ("gastos_compromiso", models.CharField(max_length=30)),
                ("esterilizacion_compromiso", models.CharField(max_length=10)),
                ("planes_futuro", models.TextField()),
                ("declaracion_verdadera", models.BooleanField()),
                ("acepto_terminos", models.BooleanField()),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
