# Generated by Django 5.2.3 on 2025-07-12 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0010_solicitudadopcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudadopcion",
            name="mascota",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to="adopciones.mascotaenadopcion",
            ),
        ),
    ]
