# Generated by Django 5.2.3 on 2025-07-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0011_solicitudadopcion_mascota"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudadopcion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aprobada", "Aprobada"),
                    ("rechazada", "Rechazada"),
                    ("contactado", "Contactado"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="solicitudadopcion",
            name="fecha_contacto",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitudadopcion",
            name="fecha_rechazo",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
