# Generated by Django 5.2.3 on 2025-07-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0014_solicitudadopcion_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascotaabandonada",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mascotaabandonada",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Perro"), ("gato", "Gato")],
                default="perro",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="mascotaabandonada",
            name="lugar_encontrado",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="mascotaabandonada",
            name="region",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
