# Generated by Django 5.2.3 on 2025-07-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adopciones", "0016_alter_mascotaabandonada_ciudad_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitudadopcion",
            name="num_ninos",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
