# Generated by Django 5.2.3 on 2025-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_rename_creado_producto_fecha_creacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
