# Generated by Django 5.2.3 on 2025-07-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="estado",
            field=models.CharField(
                choices=[("publicado", "Publicado"), ("oculto", "Oculto")],
                default="publicado",
                max_length=10,
            ),
        ),
    ]
