# Generated by Django 5.2.3 on 2025-07-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmacias", "0001_initial"),
        ("ubicacion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmacia",
            name="ciudad",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="ubicacion.ciudad",
            ),
            preserve_default=False,
        ),
    ]
