# Generated by Django 5.2.3 on 2025-07-16 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_profile_ciudad_alter_profile_region"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_tutor", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="HorarioAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.CharField(
                        choices=[
                            ("Lunes", "Lunes"),
                            ("Martes", "Martes"),
                            ("Miércoles", "Miércoles"),
                            ("Jueves", "Jueves"),
                            ("Viernes", "Viernes"),
                            ("Sábado", "Sábado"),
                            ("Domingo", "Domingo"),
                        ],
                        max_length=15,
                    ),
                ),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="accounts.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_mascota", models.CharField(max_length=100)),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("perro", "Canino"),
                            ("gato", "Felino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raza", models.CharField(blank=True, max_length=100, null=True)),
                ("edad", models.PositiveIntegerField()),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Macho", "Macho"), ("Hembra", "Hembra")],
                        max_length=10,
                    ),
                ),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "propietario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mascotas_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to="clinicas.tutor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_consulta",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("urgencia", "Urgencia"),
                            ("control", "Control"),
                            ("vacunacion", "Vacunación"),
                            ("otro", "Otro"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("motivo", models.TextField()),
                ("diagnostico", models.TextField(blank=True, null=True)),
                ("tratamiento", models.TextField(blank=True, null=True)),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "temperatura",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("frecuencia_cardiaca", models.IntegerField(blank=True, null=True)),
                ("frecuencia_respiratoria", models.IntegerField(blank=True, null=True)),
                ("proxima_cita", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("cerrada", "Cerrada"),
                            ("pendiente", "Pendiente"),
                        ],
                        default="abierta",
                        max_length=10,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "clinica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultas_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas",
                        to="clinicas.mascota",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="HistorialVacuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_aplicacion", models.DateField()),
                ("proxima_dosis", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicas.mascota",
                    ),
                ),
                (
                    "vacuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinicas.vacuna",
                    ),
                ),
            ],
        ),
    ]
