# Generated by Django 5.2.3 on 2025-07-04 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_profile_direccion_profile_nombre_clinica_and_more"),
        ("clinicas", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="horarioatencion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="horarioatencion",
            name="profile",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="horarios",
                to="accounts.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="horarioatencion",
            name="dia",
            field=models.CharField(
                choices=[
                    ("Lunes", "Lunes"),
                    ("Martes", "Martes"),
                    ("Miércoles", "Miércoles"),
                    ("Jueves", "Jueves"),
                    ("Viernes", "Viernes"),
                    ("Sábado", "Sábado"),
                    ("Domingo", "Domingo"),
                ],
                max_length=15,
            ),
        ),
        migrations.RemoveField(
            model_name="horarioatencion",
            name="clinica",
        ),
    ]
