# Generated by Django 5.2.3 on 2025-07-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("consulta", "Consulta"),
                            ("vacuna", "Vacuna"),
                            ("cirugia", "Cirugía"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
