# Generated by Django 5.2.3 on 2025-07-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0004_mascota_clinica_alter_mascota_propietario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Canino"), ("gato", "Felino"), ("otro", "Otro")],
                max_length=20,
            ),
        ),
    ]
