# Generated by Django 5.2.3 on 2025-07-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0005_alter_mascota_especie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="raza",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
