# Generated by Django 5.2.3 on 2025-07-15 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinicas", "0006_alter_mascota_raza"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consulta",
            options={"ordering": ["-fecha"]},
        ),
        migrations.AddField(
            model_name="consulta",
            name="clinica",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consulta",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierta", "Abierta"),
                    ("cerrada", "Cerrada"),
                    ("pendiente", "Pendiente"),
                ],
                default="abierta",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="frecuencia_cardiaca",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="frecuencia_respiratoria",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="peso_kg",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="proxima_cita",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consulta",
            name="temperatura",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=4, null=True
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tipo_consulta",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("urgencia", "Urgencia"),
                    ("control", "Control"),
                    ("vacunacion", "Vacunación"),
                    ("otro", "Otro"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="veterinario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas_realizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="diagnostico",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="fecha",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="mascota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultas",
                to="clinicas.mascota",
            ),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="motivo",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="tratamiento",
            field=models.TextField(blank=True, null=True),
        ),
    ]
