# Generated by Django 5.2.3 on 2025-07-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="creada_por_clinica",
            field=models.BooleanField(default=False),
        ),
    ]
