# Generated by Django 5.2.3 on 2025-07-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0002_reserva_creada_por_clinica"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aceptada", "Aceptada"),
                    ("rechazada", "Rechazada"),
                ],
                default="pendiente",
                max_length=10,
            ),
        ),
    ]
