# Generated by Django 5.2.3 on 2025-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0004_reserva_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="Raza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("perro", "Canino"),
                            ("gato", "Felino"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "unique_together": {("nombre", "especie")},
            },
        ),
    ]
