# Generated by Django 5.2.3 on 2025-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0005_raza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raza",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Canino"), ("gato", "Felino")], max_length=20
            ),
        ),
    ]
