# Generated by Django 5.2.3 on 2025-07-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0006_alter_raza_especie"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="raza",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="raza",
            name="especie",
            field=models.CharField(
                choices=[("perro", "Canino"), ("gato", "Felino"), ("otro", "Otro")],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="raza",
            constraint=models.UniqueConstraint(
                fields=("nombre", "especie"), name="unique_raza_especie"
            ),
        ),
    ]
