# Generated by Django 5.2.3 on 2025-07-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservas", "0007_alter_raza_unique_together_alter_raza_especie_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="es_urgente",
            field=models.BooleanField(default=False),
        ),
    ]
